spring:
  application:
    name: nacid-backoffice-core-be
  profiles:
    active: '@activeProfile@'
  cache:
    jcache:
      config: classpath:ehcache.xml

---
spring:
  config:
    activate.on-profile:
      - dev
      - office
    import: configserver:http://192.168.3.84:8301/nacid-config-server

---
spring:
  config:
    activate.on-profile:
      - stage
      - production
    import: configserver:http://172.16.1.97:8301/nacid-config-server