package bg.duosoft.email.nacidemailproducer.enums;

public enum MailTemplate {
    NEW_PORTAL_ACCOUNT_ADMIN,
    FORGOTTEN_USERNAME,
    ACCOUNT_ACTIVATION,
    RESET_PASSWORD,
    CHANGE_EMAIL,
    CHANGE_PASSWORD,
    APPLICATION_SUBMITTED,
    APPLICATION_ACCEPTED,
    APPLICATION_REVERTED_DRAFT,
    RESPONSIBLE_USER_CHANGE,
    MIGRATED_ACCOUNTS_RESET_PASSWORD,

    LIBSERV_APP_SUBMISSION_ADMIN,
    PAYMENTS_ERROR_ADMIN,
    UPDATE_LIABILITY_NOTIFICATION,
    INSERT_LIABILITY_NOTIFICATION,
    DELETE_LIABILITY_NOTIFICATION,
    PAID_LIABILITY_NOTIFICATION,
    CORRESPONDENCE_NOTIFICATION,
    AR_UNI_REGISTER_UPDATED_ADMIN,
    ADDITIONAL_DOCUMENTS_RECEIVED,
    ORIGINAL_PROVIDED_DOCUMENTS_NOTIFICATION;
}
