<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>bg.duosoft</groupId>
    <artifactId>nacid-cronjob</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>nacid-cronjob</name>
    <description>nacid-cronjob</description>
    <properties>
        <java.version>17</java.version>
        <cronjob.version>6.0-SNAPSHOT</cronjob.version>
        <email.producer.version>1.0.0-SNAPSHOT</email.producer.version>
        <lombok.version>1.18.24</lombok.version>
		<spring.boot.version>2.7.1</spring.boot.version>
    </properties>
    <dependencies>
		<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
		
        <dependency>
            <groupId>bg.duosoft.email</groupId>
            <artifactId>nacid-email-producer</artifactId>
            <version>${email.producer.version}</version>
        </dependency>
		
		<dependency>
            <groupId>bg.duosoft</groupId>
            <artifactId>cronjob</artifactId>
            <version>${cronjob.version}</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <forceJavacCompilerUse>true</forceJavacCompilerUse>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
   <distributionManagement>
        <repository>
			<id>sirma-releases</id>
			<url>https://nexus.devzone.sirma.bg/repository/maven-releases/</url>
		</repository>

		<snapshotRepository>
			<id>sirma-snapshots</id>
			<url>https://nexus.devzone.sirma.bg/repository/maven-snapshots/</url>
		</snapshotRepository>
    </distributionManagement>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
