rabbitMQ:
  host: localhost
  port: 5672
  username: guest
  password: guest
  email:
    vhost: nacid-email
    routekey: email-routekey
    queue:
      name: email-queue
    exchange:
      name: email-exchange
    wait-queue:
      name: email-queue.wait
      ttl: 10000 #10sec
    parking-lot-queue:
      name: email-queue.parkingLot


pdb:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://duosoft2.abbaty.int:5432/nacid_public
    username: postgres
    password: p0stGr#s
    maximum-pool-size: 3
  hibernate:
    show_sql: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
