package bg.duosoft.nacidcoreapi.validation.nomenclatures.base;

import bg.duosoft.nacidcoreapi.service.nomenclature.base.NomenclatureServiceBase;
import bg.duosoft.nacidfrontofficedto.nomenclature.base.NomenclatureBase;
import bg.duosoft.nacidfrontofficedto.nomenclature.filter.base.BaseNomenclatureFilterDTO;
import bg.duosoft.nacidshareddata.validation.config.ValidationError;
import bg.duosoft.nacidshareddata.validation.config.Validator;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import org.springframework.util.CollectionUtils;
import org.springframework.util.StringUtils;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

@Slf4j
@Component
@RequiredArgsConstructor
public abstract class BaseNomenclatureValidator<ID extends Serializable, D extends NomenclatureBase<ID>, F extends BaseNomenclatureFilterDTO<ID>> implements Validator<D> {

    protected Integer getIdLength() {
        return 4;
    }

    protected Integer getNameLength() {
        return 255;
    }

    protected void validateAdditional(List<ValidationError> errors, D obj, Object... args) {
    }

    @Override
    public List<ValidationError> validate(D obj, Object... args) {
        List<ValidationError> errors = new ArrayList<>();

        validateId(errors, obj.getId(), (Boolean) args[0], (NomenclatureServiceBase<ID, D, F>) args[1]);
        validateName(errors, obj.getName());
        validateIsActive(errors, obj.getIsActive());
        validateAdditional(errors, obj);

        return errors;
    }

    private void validateId(List<ValidationError> errors, ID id, Boolean isCreate, NomenclatureServiceBase<ID, D, F> service) {
        rejectIfEmptyString(errors, id.toString(), "id", "validation.field.required");
        if (StringUtils.hasText(id.toString())) {
            rejectIfTrue(errors, id.toString().length() > getIdLength(), "id", "validation.charCount.invalid." + getIdLength());
        }

        if (isCreate) { //isCreate
            if (StringUtils.hasText(id.toString())) {
                D dto = service.selectById(id);
                if (Objects.nonNull(dto)) {
                    reject(errors, "id", "validation.id.taken");
                }
            }
        } else { //isEdit
            if (StringUtils.hasText(id.toString())) {
                D dto = service.selectById(id);
                if (Objects.isNull(dto)) {
                    reject(errors, "id", "validation.field.invalid");
                }
            }
        }
    }

    protected void validateNumberId(List<ValidationError> errors, ID id, boolean isCreate, boolean isAutogeneratedId, NomenclatureServiceBase<ID, D, F> service) {
        if (Objects.nonNull(id)) {
            rejectIfTrue(errors, id.toString().length() > getIdLength(), "id", "validation.charCount.invalid." + getIdLength());
        }
        if (CollectionUtils.isEmpty(errors)) {
            if (isCreate) { //isCreate
                if (isAutogeneratedId) {
                    rejectIfTrue(errors, Objects.nonNull(id), "id", "validation.autogenerated.id");
                } else {
                    rejectIfEmpty(errors, id, "id", "validation.field.required");
                }

                if (Objects.nonNull(id)) {
                    D dto = service.selectById(id);
                    if (Objects.nonNull(dto)) {
                        reject(errors, "id", "validation.id.taken");
                    }
                }
            } else { //isEdit
                rejectIfEmpty(errors, id, "id", "validation.field.required");
                if (Objects.nonNull(id)) {
                    D dto = service.selectById(id);
                    if (Objects.isNull(dto)) {
                        reject(errors, "id", "validation.field.invalid");
                    }
                }
            }
        }

    }

    protected void validateName(List<ValidationError> errors, String name) {
        rejectIfEmptyString(errors, name, "name", "validation.field.required");
        if (StringUtils.hasText(name)) {
            rejectIfTrue(errors, name.length() > getNameLength(), "name", "validation.charCount.invalid." + getNameLength());
        }
    }

    protected void validateIsActive(List<ValidationError> errors, Boolean isActive) {
        rejectIfEmptyBoolean(errors, isActive, "isActive", "validation.field.required");
    }
}
