package bg.duosoft.nacid.backoffice.rudi.be.validator.application;

public enum ValidationScope {
    FINAL,
    MAIN_DATA,
    EDUCATION_DATA,
    STATUS_DATA,
    COMMISSION_MEMBER,
    COMMISSION_MEMBER_STATEMENT,
    COMMISSION_CALENDAR_PROCESS_DATA,
    RESPONSIBLE_USER,
    RECEPTION,
    E_APPS_ACCEPTANCE,
    UNIVERSITY_EXAMINATION,
    PROGRAM_EXAMINATION,
    DIPLOMA_EXAMINATION,
    TRAINING_LOCATION_EXAMINATION,
    APP_ATTACHMENTS,
    NO_VALIDATION,
}
