<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>bg.duosoft.nacid</groupId>
    <artifactId>nacid-common-dto</artifactId>
    <packaging>pom</packaging>
	<version>1.0.0-SNAPSHOT</version>
	
    <modules>
		<module>nacid-minio-dto</module>
		<module>nacid-frontoffice-dto</module>
		<module>nacid-backoffice-core-data-dto</module>
		<module>nacid-shared-dto</module>
    </modules>

 
    <dependencyManagement>
		<dependencies>
		</dependencies>
	</dependencyManagement>

    <distributionManagement>
        <repository>
			<id>sirma-releases</id>
			<url>https://nexus.devzone.sirma.bg/repository/maven-releases/</url>
		</repository>

		<snapshotRepository>
			<id>sirma-snapshots</id>
			<url>https://nexus.devzone.sirma.bg/repository/maven-snapshots/</url>
		</snapshotRepository>
    </distributionManagement>
</project>
