<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>bg.duosoft.nacid</groupId>
    <artifactId>nacid-backoffice-core-be</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>nacid-backoffice-core-be</name>
    <description>nacid-backoffice-core-be</description>
    <properties>
        <java.version>17</java.version>
        <swagger.version>3.0.0</swagger.version>
        <io.minio.version>8.3.7</io.minio.version>
        <com.squareup.okhttp3.version>4.9.3</com.squareup.okhttp3.version>
        <spring.cloud.version>2021.0.3</spring.cloud.version>
        <nacid.backoffice.shared.data.version>1.0.0-SNAPSHOT</nacid.backoffice.shared.data.version>
        <nacid.payments.client>1.0.0-SNAPSHOT</nacid.payments.client>
        <org.mapstruct.version>1.4.2.Final</org.mapstruct.version>
        <logging.extras.version>2.0-SNAPSHOT</logging.extras.version>
        <nacid.rudi.client.version>0.0.1-SNAPSHOT</nacid.rudi.client.version>
        <nacid.regprof.client.version>0.0.1-SNAPSHOT</nacid.regprof.client.version>
        <nacid.libserv.client.version>0.0.1-SNAPSHOT</nacid.libserv.client.version>
    </properties>
    <profiles>
        <profile>
            <id>dev</id>
            <properties>
                <activeProfile>dev</activeProfile>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>office</id>
            <properties>
                <activeProfile>office</activeProfile>
            </properties>
        </profile>
        <profile>
            <id>stage</id>
            <properties>
                <activeProfile>stage</activeProfile>
            </properties>
        </profile>
        <profile>
            <id>production</id>
            <properties>
                <activeProfile>production</activeProfile>
            </properties>
        </profile>
    </profiles>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.loki4j</groupId>
            <artifactId>loki-logback-appender</artifactId>
            <version>1.4.1</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-boot-starter</artifactId>
            <version>${swagger.version}</version>
        </dependency>
        <dependency>
            <groupId>bg.duosoft</groupId>
            <artifactId>nacid-backoffice-shared-data</artifactId>
            <version>${nacid.backoffice.shared.data.version}</version>
        </dependency>
        <dependency>
            <groupId>bg.duosoft.nacid</groupId>
            <artifactId>nacid-payments-client</artifactId>
            <version>${nacid.payments.client}</version>
        </dependency>
        <dependency>
            <groupId>bg.duosoft</groupId>
            <artifactId>nacid-minio-services</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>${com.squareup.okhttp3.version}</version>
        </dependency>
        <dependency>
            <groupId>bg.duosoft.nacid</groupId>
            <artifactId>nacid-backoffice-rudi-client</artifactId>
            <version>${nacid.rudi.client.version}</version>
        </dependency>

        <dependency>
            <groupId>bg.duosoft.nacid</groupId>
            <artifactId>nacid-backoffice-regprof-client</artifactId>
            <version>${nacid.regprof.client.version}</version>
        </dependency>

        <dependency>
            <groupId>bg.duosoft.nacid</groupId>
            <artifactId>nacid-backoffice-libserv-client</artifactId>
            <version>${nacid.libserv.client.version}</version>
        </dependency>

        <dependency>
            <groupId>javax.cache</groupId>
            <artifactId>cache-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>


        <dependency>
            <groupId>bg.duosoft.logging</groupId>
            <artifactId>logging-extras-db</artifactId>
            <version>${logging.extras.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${org.mapstruct.version}</version>
        </dependency>

        <dependency>
            <groupId>e-iceblue</groupId>
            <artifactId>spire.doc.free</artifactId>
            <version>5.2.0</version>
        </dependency>



    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring.cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <finalName>${artifactId}</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/*.properties</include>
                    <include>**/*.xml</include>
                    <include>**/*.yml</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <forceJavacCompilerUse>true</forceJavacCompilerUse>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
