package bg.duosoft.nacidbackofficeshareddata.validator;

import bg.duosoft.nacid.backoffice.core.data.domain.rest.nomenclatures.base.NomenclatureBase;
import bg.duosoft.nacid.backoffice.core.data.domain.rest.nomenclatures.filter.base.BaseNomenclatureFilterDTO;
import bg.duosoft.nacidbackofficeshareddata.service.NomenclatureServiceBase;
import bg.duosoft.nacidshareddata.validation.config.ValidationError;
import bg.duosoft.nacidshareddata.validation.config.Validator;
import org.springframework.util.CollectionUtils;

import java.util.List;
import java.util.Objects;

/**
 * User: ggeorgiev
 * Date: 11.10.2022
 * Time: 15:46
 */
public abstract class BaseIntegerKeyNomenclatureValidator<D extends NomenclatureBase<Integer>, F extends BaseNomenclatureFilterDTO<Integer>> extends BaseNomenclatureValidator<Integer, D, F> implements Validator<D> {

    protected void validateId(List<ValidationError> errors, Integer id, boolean isCreate, NomenclatureServiceBase<Integer, D, F> service) {
        if (Objects.nonNull(id)) {
            rejectIfTrue(errors, id.toString().length() > getIdLength(), "id", "validation.charCount.invalid." + getIdLength());
        }
        if (CollectionUtils.isEmpty(errors)) {
            if (isCreate) { //isCreate
                rejectIfTrue(errors, Objects.nonNull(id), "id", "validation.autogenerated.id");
                if (Objects.nonNull(id)) {
                    D dto = service.selectById(id);
                    if (Objects.nonNull(dto)) {
                        reject(errors, "id", "validation.id.taken");
                    }
                }
            } else { //isEdit
                rejectIfEmpty(errors, id, "id", "validation.field.required");
                if (Objects.nonNull(id)) {
                    D dto = service.selectById(id);
                    if (Objects.isNull(dto)) {
                        reject(errors, "id", "validation.field.invalid");
                    }
                }
            }
        }

    }
}
