--liquibase formatted sql

--changeset veizov:core_0002
--validCheckSum: 8:5b26913fcab512073998d53aabe5fec2
--validCheckSum: 8:00528ee0f732a13a10e066b97946f63f
create table nomenclatures.country
(
    code  varchar(2)   not null
        constraint country_pk
            primary key,
    name          varchar(255) not null,
    official_name varchar(255) not null,
    active        integer      not null
);

INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CS', 'Сърбия и Черна гора', 'Сърбия и Черна гора', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AI', 'Ангуила', 'Ангила', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SU', 'СССР', 'СССР', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('--', 'Неопределан', 'Неопределан', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AU', 'Австралия', 'Австралийски съюз', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('DZ', 'Алжир', 'Алжирска демократична народна република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AF', 'Афганистан', 'Ислямска република Афганистан', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BO', 'Боливия', 'Многонационална държава Боливия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BR', 'Бразилия', 'Федеративна република Бразилия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GM', 'Гамбия', 'Република Гамбия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GY', 'Гвиана', 'Кооперативна република Гвиана', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('DE', 'Германия', 'Федерална република Германия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CD', 'Демократична Република Конго', 'Демократична република Конго', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CM', 'Камерун', 'Република Камерун', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('RW', 'Руанда', 'Република Руанда', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('RO', 'Румъния', 'Румъния', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('WS', 'Самоа', 'Независима държава Самоа', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SM', 'Сан Марино', 'Република Сан Марино', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SZ', 'Свазиленд', 'Кралство Свазиленд', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SJ', 'Острови Свалбард и Жан Майен', 'Свалбард и Ян Майен', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SH', 'Санта Хелена', 'Света Елена', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MP', 'Северни Мариански острови', 'Общност Северни Мариански острови', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('VC', 'Сейнт Винсент и Гренадини', 'Сейнт Винсънт и Гренадини', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('KN', 'Сейнт Китс (Кристофер) и Невис', '', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('LC', 'Санта Лучия', 'Сейнт Лусия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GQ', 'Екваториална Гвинея', 'Република Екваториална Гвинея', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('ID', 'Индонезия', 'Република Индонезия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('IS', 'Исландия', 'Република Исландия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CV', 'Кабо Верде', 'Република Кабо Верде', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('KG', 'Киргизстан', 'Киргизка република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CC', 'Кокосови острови', 'Кокосови острови', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CI', 'Кот д'' Ивоар', 'Република Кот д', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('LA', 'Лаос', 'Лаоска народнодемократична република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('LI', 'Лихтенщайн', 'Княжество Лихтенщайн', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MR', 'Мавритания', 'Ислямска република Мавритания', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MO', 'Макао', 'Специален административен', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MA', 'Мароко', 'Кралство Мароко', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('FM', 'Микронезия', 'Федеративни щати Микронезия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('NE', 'Нигер', 'Република Нигер', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('NL', 'Нидерландия', 'Кралство Нидерландия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('NF', 'Норфолски острови', 'Територия остров Норфолк', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('PG', 'Папуа Нова Гвинея', 'Независима държава Папуа-Нова Гвинея', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('RU', 'Руска федерация', 'Руска федерация', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SA', 'Саудитска Арабия', 'Кралство Саудитска Арабия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('KP', 'Северна Корея', 'Корейска народнодемократична република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SY', 'Сирийска арабска република', 'Сирийска арабска република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TG', 'Того', 'Република Того', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TT', 'Тринидад и Тобаго', 'Тринидад и Тобаго', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('HN', 'Хондурас', 'Република Хондурас', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('HM', 'Острови Харт и МакДоналд', 'Хърд и Макдоналд', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('LK', 'Шри Ланка', 'Демократична социалистическа република Шри Ланка', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GS', 'Сендуичови острови', 'Южна Джорджия и Южни Сандвичеви острови', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AT', 'Австрия', 'Република Австрия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AG', 'Антигуа и Барбуда', 'Антигуа и Барбуда', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AR', 'Аржентина', 'Република Аржентина', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AM', 'Армения', 'Република Армения', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AW', 'Аруба', 'Аруба', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BD', 'Бангладеш', 'Народна република Бангладеш', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BB', 'Барбадос', 'Барбадос', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BS', 'Бахами', 'Бахамска общност', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BH', 'Бахрейн', 'Кралство Бахрейн', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BY', 'Беларус', 'Република Беларус', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BE', 'Белгия', 'Кралство Белгия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BZ', 'Белиз', 'Белиз', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BJ', 'Бенин', 'Република Бенин', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BM', 'Бермудски острови', 'Бермуда', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BT', 'Бутан', 'Кралство Бутан', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CF', 'Централна Африканска Република', 'Централноафриканска република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TF', 'Френски Южни територии', 'Френски Южни територии', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('KR', 'Южна Корея', 'Южна Корея', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MK', 'Македония', 'Македония', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BW', 'Ботсвана', 'Република Ботсуана', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('IO', 'Британска Индия', 'Британски територии в Индийския океан', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BN', 'Бруней Дарусалем', 'Бруней Даруссалам', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BF', 'Буркина Фасо', 'Буркина Фасо', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BI', 'Бурунди', 'Република Бурунди', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BG', 'България', 'Република България', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GA', 'Габон', 'Република Габон', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GH', 'Гана', 'Република Гана', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GP', 'Гваделупа', 'Гваделупа', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GT', 'Гватемала', 'Република Гватемала', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GN', 'Гвинеа', 'Република Гвинея', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GW', 'Гвинеа Бисау', 'Република Гвинея Бисау', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GI', 'Гибралтар', 'Гибралтар', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GD', 'Гренада', 'Гренада', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GL', 'Гренландия', 'Гренландия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GE', 'Грузия', 'Грузия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GU', 'Гуам', 'Гуам', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GG', 'Гернис', 'Департамент Гърнзи', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('DK', 'Дания', 'Кралство Дания', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('DJ', 'Джибути', 'Република Джибути', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('JE', 'Джърси', 'Департамент Джърси', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('DM', 'Доминика', 'Доминиканска общност', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('DO', 'Доминиканска Република', 'Доминиканска република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('EG', 'Египет', 'Арабска република Египет', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SV', 'Ел Салвадор', 'Република Ел Салвадор', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('EC', 'Еквадор', 'Република Еквадор', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('ER', 'Еритрея', 'Държавата Еритрея', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('EE', 'Естония', 'Република Естония', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('ET', 'Етиопия', 'Федерална демократична република Етиопия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('IL', 'Израел', 'Държавата Израел', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('IN', 'Индия', 'Република Индия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('IQ', 'Ирак', 'Република Ирак', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('IR', 'Иран', 'Ислямска република Иран', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('IE', 'Ирландия', 'Ирландия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('IT', 'Италия', 'Италианска република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BA', 'Босна и Херцеговина', 'Босна и Херцеговина', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('KZ', 'Казахстан', 'Република Казахстан', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('KY', 'Кайманови Острови', 'Кайманови острови', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('KH', 'Камбоджа', 'Кралство Камбоджа', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CA', 'Канада', 'Канада', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('KE', 'Кения', 'Република Кения', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CY', 'Кипър', 'Република Кипър', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('KI', 'Кирибати', 'Република Кирибати', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CN', 'Китай', 'Китайска народна република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CO', 'Колумбия', 'Република Колумбия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('KM', 'Коморски острови', 'Съюз на Коморските острови', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CG', 'Конго', 'Република Конго', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CR', 'Коста Рика', 'Република Коста Рика', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CU', 'Куба', 'Република Куба', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('KW', 'Кувейт', 'Държавата Кувейт', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('LV', 'Латвия', 'Република Латвия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('LS', 'Лесото', 'Кралство Лесото', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('LR', 'Либерия', 'Република Либерия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('LY', 'Либия', 'Либия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('LB', 'Ливан', 'Ливанска република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('LT', 'Литва', 'Република Литва', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('LU', 'Люксембург', 'Велико херцогство Люксембург', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MG', 'Мадагаскар', 'Република Мадагаскар', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MS', 'Монтсерат', 'Монтсерат', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('BV', 'Буветски острови', 'Остров Буве', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('IM', 'Айл ъф Мен', 'Остров Ман', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CX', 'Коледни острови', 'Територия остров Рождество', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CK', 'Кукови острови', 'Острови Кук', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('HU', 'Унгария', 'Унгария', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('FO', 'Фарорски острови', 'Фарьорски острови', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('FJ', 'Фуджи', 'Република Фиджи', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('FI', 'Финландия', 'Република Финландия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('FK', 'Фолклендски острови', 'Фолкландски острови', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('FR', 'Франция', 'Френска република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GF', 'Френска Гвиана', 'Френска Гвиана', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('PF', 'Френска Полинезия', 'Френска Полинезия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('HT', 'Хаити', 'Република Хаити', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('HK', 'Хонг Конг', 'Специален административен', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('HR', 'Хърватска', 'Република Хърватия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TD', 'Чад', 'Република Чад', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CZ', 'Чехия', 'Чешка република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CL', 'Чили', 'Република Чили', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('JM', 'Ямайка', 'Ямайка', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GR', 'Гърция', 'Гръцка република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('JO', 'Йордания', 'Хашемитско кралство Йордания', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AN', 'Холандски Антили', 'Холандски Антили', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('PS', 'Палестина', 'Палестина', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('PN', 'Острови Питкерн', 'Острови Питкерн', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('ST', 'Сан Томе и Принсипи', 'Сан Томе и Принсипи', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AL', 'Албания', 'Република Албания', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AO', 'Ангола', 'Република Ангола', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AD', 'Андора', 'Княжество Андора', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AQ', 'Антарктика', 'Антарктика', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TL', 'Източен Тимор', 'Демократична република Източен Тимор', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('ES', 'Испания', 'Кралство Испания', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('QA', 'Катар', 'Държавата Катар', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MU', 'Мавриций', 'Република Мавриций', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('YT', 'Майоте', 'Майот', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MW', 'Малави', 'Република Малави', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MY', 'Малайзия', 'Малайзия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MV', 'Малдиви', 'Република Малдиви', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('ML', 'Мали', 'Република Мали', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MT', 'Малта', 'Република Малта', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MQ', 'Мартиника', 'Мартиника', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MH', 'Маршалски острови', 'Република Маршалови острови', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MX', 'Мексико', 'Мексикански съединени щати', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MM', 'Мианмар', '', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('PR', 'Пуерто Рико', 'Пуерториканска общност', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MD', 'Молдова', 'Република Молдова', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MC', 'Монако', 'Княжество Монако', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MN', 'Монголия', 'Монголия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('NA', 'Намибия', 'Република Намибия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('NR', 'Науру', 'Република Науру', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('NP', 'Непал', 'Непал', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('NG', 'Нигерия', 'Федерална република Нигерия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('NI', 'Никарагуа', 'Република Никарагуа', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('NU', 'Ний', 'Ниуе', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('NZ', 'Нова Зеландия', 'Нова Зеландия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('NC', 'Нова Каледония', 'Нова Каледония', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('NO', 'Норвегия', 'Кралство Норвегия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('OM', 'Оман', 'Султанат Оман', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('PK', 'Пакистан', 'Ислямска република Пакистан', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('PW', 'Палау (Белау)', 'Република Палау', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('PA', 'Панама', 'Република Панама', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('PY', 'Парагвай', 'Република Парагвай', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('PE', 'Перу', 'Република Перу', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('PL', 'Полша', 'Република Полша', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('PT', 'Португалия', 'Португалска република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AZ', 'Азeрбайджан', 'Азербайджанска република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('RE', 'Рейюнион', 'Реюнион', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SC', 'Сейшелски острови', 'Република Сейшели', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('PM', 'Сейнт Пиер и Мигелин', 'Териториална общност Сен Пиер и Микелон', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SN', 'Сенегал', 'Република Сенегал', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SL', 'Сиера Леоне', 'Република Сиера Леоне', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SG', 'Сингапур', 'Република Сингапур', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SK', 'Словакия', 'Словашка република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SI', 'Словения', 'Република Словения', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SB', 'Соломонови острови', 'Соломонови острови', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SO', 'Сомалия', 'Република Сомалия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SD', 'Судан', 'Република Судан', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SR', 'Суринам', 'Република Суринам', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TJ', 'Таджикистан', 'Република Таджикистан', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TW', 'Тайван', 'Китайска република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TH', 'Тайланд', 'Кралство Тайланд', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TZ', 'Танзания', 'Обединена република Танзания', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TK', 'Токелау', 'Токелау', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TO', 'Тонга', 'Кралство Тонга', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TN', 'Тунис', 'Тунизийска република', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TM', 'Туркменистан', 'Туркменистан', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TR', 'Турция', 'Република Турция', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TC', 'Туркс и Кайгоски о-ви', 'Търкс и Кайкос', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('PH', 'Филипини', 'Република Филипини', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('CH', 'Швейцария', 'Конфедерация Швейцария', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('SE', 'Швеция', 'Кралство Швеция', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('ZA', 'Южна Африка', 'Република Южна Африка', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('MZ', 'Мозамбик', 'Република Мозамбик', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('VA', 'Ватикана', 'Ватикана', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('YU', 'Югославия', 'Югославия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('UZ', 'Узбекистан', 'Република Узбекистан', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('UA', 'Украйна', 'Украйна', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('WF', 'Острови Уалис и Футуна', 'Уолис и Футуна', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('UY', 'Уругвай', 'Източна република Уругвай', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('ME', 'Черна гора', 'Черна гора', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('JP', 'Япония', 'Япония', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('GB', 'Великобритания', 'Обединено кралство Великобритания', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AS', 'Самоа (Ам.)', 'Американска Самоа', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('VI', 'Вирджински острови (САЩ)', 'Американски Вирджински острови', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('VU', 'Вануату', 'Република Вануату', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('VE', 'Венецуела', 'Боливарска република Венецуела', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('VN', 'Виетнам', 'Социалистическа република Виетнам', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('VG', 'Вирджински острови (Брит.)', 'Британски Вирджински острови', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('ZM', 'Замбия', 'Република Замбия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('EH', 'Западна Сахара', 'Западна Сахара', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('ZW', 'Зимбабве', 'Република Зимбабве', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('YE', 'Йемен', 'Република Йемен', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('UM', 'Острови - САЩ', 'Малки отдалечени острови на Съединените щати', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('AE', 'Обединени Арабски Емирства', 'Обединени арабски емирства', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('US', 'САЩ', 'Съединени американски щати', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('RS', 'Сърбия', 'Република Сърбия', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('TV', 'Тувалу', 'Тувалу', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('UG', 'Уганда', 'Република Уганда', 1);
INSERT INTO nomenclatures.country (code, name, official_name, active) VALUES ('XK', 'Косово', 'Република Косово', 1);