--liquibase formatted sql

--changeset ndimov:core_0078
UPDATE nomenclatures.country SET name_en = 'Caribbean Netherlands' WHERE name = 'Карибска Нидерландия';
UPDATE nomenclatures.country SET name_en = 'Anguilla' WHERE name = 'Ангуила';
UPDATE nomenclatures.country SET name_en = 'Samoa' WHERE name = 'Самоа';
UPDATE nomenclatures.country SET name_en = 'Svalbard and Jan Mayen Islands' WHERE name = 'Острови Свалбард и Жан Майен';
UPDATE nomenclatures.country SET name_en = 'Saint Helena' WHERE name = 'Санта Хелена';
UPDATE nomenclatures.country SET name_en = 'Northern Mariana Islands' WHERE name = 'Северни Мариански острови';
UPDATE nomenclatures.country SET name_en = 'Cabo Verde' WHERE name = 'Кабо Верде';
UPDATE nomenclatures.country SET name_en = 'Cocos (Keeling) Islands' WHERE name = 'Кокосови острови';
UPDATE nomenclatures.country SET name_en = 'Micronesia (Federated States of Micronesia)' WHERE name = 'Микронезия';
UPDATE nomenclatures.country SET name_en = 'Norfolk Island' WHERE name = 'Норфолски острови';
UPDATE nomenclatures.country SET name_en = 'Trinidad and Tobago' WHERE name = 'Тринидад и Тобаго';
UPDATE nomenclatures.country SET name_en = 'Heard Island and McDonald Islands' WHERE name = 'Острови Харт и МакДоналд';
UPDATE nomenclatures.country SET name_en = 'South Sandwich Islands' WHERE name = 'Сендуичови острови';
UPDATE nomenclatures.country SET name_en = 'Aruba' WHERE name = 'Аруба';
UPDATE nomenclatures.country SET name_en = 'Bermuda' WHERE name = 'Бермудски острови';
UPDATE nomenclatures.country SET name_en = 'French Southern Territories' WHERE name = 'Френски Южни територии';
UPDATE nomenclatures.country SET name_en = 'British Indian Ocean Territory' WHERE name = 'Британска Индия';
UPDATE nomenclatures.country SET name_en = 'Brunei Darussalam' WHERE name = 'Бруней Дарусалем';
UPDATE nomenclatures.country SET name_en = 'Guadeloupe' WHERE name = 'Гваделупа';
UPDATE nomenclatures.country SET name_en = 'USSR (Soviet Union)' WHERE name = 'СССР';
UPDATE nomenclatures.country SET name_en = 'Gibraltar' WHERE name = 'Гибралтар';
UPDATE nomenclatures.country SET name_en = 'Greenland' WHERE name = 'Гренландия';
UPDATE nomenclatures.country SET name_en = 'New Caledonia' WHERE name = 'Нова Каледония';
UPDATE nomenclatures.country SET name_en = 'Guam' WHERE name = 'Гуам';
UPDATE nomenclatures.country SET name_en = 'Guernsey' WHERE name = 'Гернис';
UPDATE nomenclatures.country SET name_en = 'Jersey' WHERE name = 'Джърси';
UPDATE nomenclatures.country SET name_en = 'Cayman Islands' WHERE name = 'Кайманови Острови';
UPDATE nomenclatures.country SET name_en = 'Kiribati' WHERE name = 'Кирибати';
UPDATE nomenclatures.country SET name_en = 'Montserrat' WHERE name = 'Монтсерат';
UPDATE nomenclatures.country SET name_en = 'Bouvet Island' WHERE name = 'Буветски острови';
UPDATE nomenclatures.country SET name_en = 'Christmas Island' WHERE name = 'Коледни острови';
UPDATE nomenclatures.country SET name_en = 'Cook Islands' WHERE name = 'Кукови острови';
UPDATE nomenclatures.country SET name_en = 'Faroe Islands' WHERE name = 'Фарорски острови';
UPDATE nomenclatures.country SET name_en = 'Falkland Islands' WHERE name = 'Фолклендски острови';
UPDATE nomenclatures.country SET name_en = 'French Guiana' WHERE name = 'Френска Гвиана';
UPDATE nomenclatures.country SET name_en = 'French Polynesia' WHERE name = 'Френска Полинезия';
UPDATE nomenclatures.country SET name_en = 'Netherlands Antilles' WHERE name = 'Холандски Антили';
UPDATE nomenclatures.country SET name_en = 'Pitcairn Islands' WHERE name = 'Острови Питкерн';
UPDATE nomenclatures.country SET name_en = 'Antarctica' WHERE name = 'Антарктика';
UPDATE nomenclatures.country SET name_en = 'Timor-Leste' WHERE name = 'Източен Тимор';
UPDATE nomenclatures.country SET name_en = 'Mayotte' WHERE name = 'Майоте';
UPDATE nomenclatures.country SET name_en = 'Maldives' WHERE name = 'Малдиви';
UPDATE nomenclatures.country SET name_en = 'Martinique' WHERE name = 'Мартиника';
UPDATE nomenclatures.country SET name_en = 'Marshall Islands' WHERE name = 'Маршалски острови';
UPDATE nomenclatures.country SET name_en = 'Nauru' WHERE name = 'Науру';
UPDATE nomenclatures.country SET name_en = 'Serbia and Montenegro' WHERE name = 'Сърбия и Черна гора';
UPDATE nomenclatures.country SET name_en = 'Saint Kitts and Nevis' WHERE name = 'Сейнт Китс и Невис';
UPDATE nomenclatures.country SET name_en = 'Hong Kong' WHERE name = 'Хонконг';
UPDATE nomenclatures.country SET name_en = 'Åland Islands' WHERE name = 'Оландски острови';
UPDATE nomenclatures.country SET name_en = 'Turkish Republic of Northern Cyprus' WHERE name = 'Турска република в Северен Кипър';
UPDATE nomenclatures.country SET name_en = 'Netherlands' WHERE name = 'Холандия';
UPDATE nomenclatures.country SET name_en = 'Sint Maarten' WHERE name = 'Синт Мартен';
UPDATE nomenclatures.country SET name_en = 'Saint Martin' WHERE name = 'Сен Мартен';
UPDATE nomenclatures.country SET name_en = 'Curaçao' WHERE name = 'Кюрасао';
UPDATE nomenclatures.country SET name_en = 'Niue' WHERE name = 'Ний';
UPDATE nomenclatures.country SET name_en = 'Palau' WHERE name = 'Палау (Белау)';
UPDATE nomenclatures.country SET name_en = 'Réunion' WHERE name = 'Рейюнион';
UPDATE nomenclatures.country SET name_en = 'Seychelles' WHERE name = 'Сейшелски острови';
UPDATE nomenclatures.country SET name_en = 'Saint Pierre and Miquelon' WHERE name = 'Сейнт Пиер и Мигелин';
UPDATE nomenclatures.country SET name_en = 'Singapore' WHERE name = 'Сингапур';
UPDATE nomenclatures.country SET name_en = 'Tokelau' WHERE name = 'Токелау';
UPDATE nomenclatures.country SET name_en = 'Tonga' WHERE name = 'Тонга';
UPDATE nomenclatures.country SET name_en = 'Turks and Caicos Islands' WHERE name = 'Туркс и Кайгоски о-ви';
UPDATE nomenclatures.country SET name_en = 'Yugoslavia' WHERE name = 'Югославия';
UPDATE nomenclatures.country SET name_en = 'Wallis and Futuna' WHERE name = 'Острови Уалис и Футуна';
UPDATE nomenclatures.country SET name_en = 'American Samoa' WHERE name = 'Самоа (Ам.)';
UPDATE nomenclatures.country SET name_en = 'United States Virgin Islands' WHERE name = 'Вирджински острови (САЩ)';
UPDATE nomenclatures.country SET name_en = 'British Virgin Islands' WHERE name = 'Вирджински острови (Брит.)';
UPDATE nomenclatures.country SET name_en = 'United States Minor Outlying Islands' WHERE name = 'Острови - САЩ';
UPDATE nomenclatures.country SET name_en = 'Tuvalu' WHERE name = 'Тувалу';
UPDATE nomenclatures.country SET name_en = 'Undefined' WHERE name = 'Неопределена';
UPDATE nomenclatures.country SET name_en = 'Saint Barthélemy' WHERE name = 'Сен Бартелми';
UPDATE nomenclatures.country SET name = 'Азербайджан' WHERE code = 'AZ';
